version: '2'
services:
  db:
    build: .
    env_file:
      - MySQL.env
  web:
    image: migoller/shinobi:latest
    env_file:
      - MySQL.env
      - Shinobi.env
    depends_on:
      - db
    ports:
      - "8080:8080"
